In [33]:
import serial # import Serial Library
import numpy as np # Import numpy
import matplotlib
import matplotlib.pyplot as plt #import matplotlib library
import time
import csv


In [63]:
arduinoData = serial.Serial('COM3', 9600) #Creating our serial object named arduinoData
# keyPressed = '' #Starts with nothing pressed


# while True: # While loop that loops forever
#for 10 sec
t_end = time.time() + 1
dataArray_ALL = np.empty((1,4)) ##fixed length based on samples

while time.time() < t_end:
    while (arduinoData.inWaiting()==0): #Wait here until there is data
        pass #do nothing
    
    arduinoString = arduinoData.readline() #read the line of text from the serial port
    dataArray = np.array(arduinoString.decode().replace('\r\n','').split('\t')).astype(np.float)   #Split it into an array called dataArray
    print(dataArray)
    
    # Seperate csv for every sample, or .mat files all together
    dataArray_ALL = np.append(dataArray_ALL, dataArray.reshape(1,-1), axis=0)    
arduinoData.close()

[ 1.    0.82  0.77 -0.52]
[ 1.    0.86  0.83 -0.83]
[ 1.    0.91  0.96 -1.07]
[ 1.    0.94  1.03 -1.28]
[ 1.    0.87  1.07 -1.42]
[ 1.    0.77  1.1  -1.39]
[ 1.    0.82  1.14 -1.06]
[ 1.    0.7   1.2  -0.74]
[ 1.    0.51  1.31 -0.54]
[ 1.    0.4   1.46 -0.37]
[ 1.    0.15  1.45 -0.47]
[ 1.   -0.02  1.29 -0.5 ]
[ 1.    0.14  0.72 -0.45]
[ 1.   -0.18 -0.05 -0.51]
[ 1.   -0.27 -0.94 -0.59]
[ 1.   -0.27 -1.75 -0.55]
[ 1.   -0.32 -2.16 -0.32]
[ 1.    0.16 -2.21  0.04]
[ 1.    0.36 -1.97  0.29]
[ 1.    0.34 -1.55  0.33]
[ 1.    0.34 -1.24  0.2 ]
[ 1.    0.27 -1.14 -0.08]
[ 1.    0.27 -1.1  -0.35]
[ 1.    0.33 -1.04 -0.52]
[ 1.    0.33 -0.98 -0.59]
[ 1.    0.35 -0.9  -0.61]
[ 1.    0.33 -0.79 -0.5 ]
[ 1.    0.33 -0.78 -0.31]
[ 1.    0.37 -0.81 -0.13]
[ 1.    0.37 -0.84 -0.1 ]
[ 1.    0.35 -0.86 -0.17]
[ 1.    0.35 -0.84 -0.25]
[ 1.    0.35 -0.88 -0.3 ]
[ 1.    0.34 -0.89 -0.34]
[ 1.    0.34 -0.95 -0.34]
[ 1.    0.3  -1.03 -0.34]
[ 1.    0.28 -1.05 -0.32]
[ 1.    0.26 -1.03 -0.26]
[ 1.    0.25

In [64]:
# field names  
fields = ['button', 'x', 'y', 'z'] 
# name of csv file  
filename = "test.csv"

np.savetxt('data.csv', dataArray_ALL, delimiter=',')